server:
  port: 9000

spring:
  application:
    name: poc-auth-server
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          # Since auth-service issues the token, it can also validate it using its own JWKS:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

app:
  jwt:
    issuer: http://localhost:9000
    access-token-minutes: 15
    refresh-token-days: 7
    # Load RSA keys from PEM (env or file). For dev you can paste PEMs into env vars.
    public-key-pem: ${JWT_PUBLIC_KEY_PEM:}
    private-key-pem: ${JWT_PRIVATE_KEY_PEM:}
    key-id: main-rsa-1
